version: '3.8'

services:
  sflab_benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      NODE_ENV: production
