export const categories = [
  { name: 'None', subcategories: [] },
  {
    name: 'Inner Top',
    subcategories: [
      {
        name: 'Shirt',
        thirdCategories: [
          { name: 'Shirt' },
          { name: 'Aloha Shirt' },
          { name: 'Cleric Shirt' },
          { name: 'Dress Shirt' },
          { name: 'Henley Neck Shirt' },
          { name: 'Ivy Shirt' },
          { name: 'Lumber Jack Shirt' },
          { name: 'Military Shirt' },
          { name: 'Open Collar Shirt' },
          { name: 'Pajama Shirt' },
          { name: 'Round Collar Shirt' },
          { name: 'Ruffle Shirt' },
          { name: 'Sports Shirt' },
          { name: 'Stand Collar Shirt' },
          { name: 'Western Shirt' },
          { name: 'Worker Shirt' },
          { name: 'Y-Neck Shirt' },
          { name: 'Polo Shirt' },
        ],
      },
      {
        name: 'Blouse',
        thirdCategories: [
          { name: 'Blouse' },
          { name: 'Peasant Blouse' },
          { name: 'Peplum Blouse' },
          { name: 'Victorian Blouse' },
          { name: 'Bow Collar Blouse' },
          { name: 'Flat Collar Blouse' },
          { name: 'Jabot Collar Blouse' },
          { name: 'Ruffled Collar Blouse' },
          { name: 'Sailor Collar Blouse' },
          { name: 'Shawl Collar Blouse' },
          { name: 'Cowl Neck Blouse' },
          { name: 'Boat Neck Blouse' },
          { name: 'Halter Neck Blouse' },
          { name: 'High Neck Blouse' },
          { name: 'Round Neck Blouse' },
          { name: 'Scoop Neck Blouse' },
          { name: 'Square Neck Blouse' },
          { name: 'V-Neck Blouse' },
          { name: 'Off-Shoulder Blouse' },
          { name: 'One-Shoulder Blouse' },
          { name: 'Shirt Blouse' },
          { name: 'Surplice Neck Blouse' },
          { name: 'Sweetheart Neck Blouse' },
          { name: 'Keyhole Neck Blouse' },
          { name: 'Slit Neck Blouse' },
          { name: 'Hooded Blouse' },
        ],
      },
      {
        name: 'T-Shirt',
        thirdCategories: [
          { name: 'T-Shirt' },
          { name: 'Hooded T-Shirt' },
          { name: 'Hoodie' },
          { name: 'Polo T-Shirt' },
          { name: 'Rugby T-Shirt' },
          { name: 'Sweatshirt' },
          { name: 'Draped T-Shirt' },
          { name: 'Sailor Collar T-Shirt' },
          { name: 'Boat Neck T-Shirt' },
          { name: 'Cowl Neck T-Shirt' },
          { name: 'Halter Neck T-Shirt' },
          { name: 'Henley Neck T-Shirt' },
          { name: 'High Neck T-Shirt' },
          { name: 'Mock Neck T-Shirt' },
          { name: 'Keyhole Neck T-Shirt' },
          { name: 'Round Neck T-Shirt' },
          { name: 'Scoop Neck T-Shirt' },
          { name: 'Slit Neck T-Shirt' },
          { name: 'Square Neck T-Shirt' },
          { name: 'Surplice Neck T-Shirt' },
          { name: 'Sweetheart Neck T-Shirt' },
          { name: 'Turtle Neck T-Shirt' },
          { name: 'V-Neck T-Shirt' },
          { name: 'Y-Neck T-Shirt' },
          { name: 'Off-Shoulder T-Shirt' },
          { name: 'One-Shoulder T-Shirt' },
        ],
      },
      {
        name: 'Sweater',
        thirdCategories: [
          { name: 'Sweater' },
          { name: 'Tilden Sweater' },
          { name: 'Hooded Sweater' },
          { name: 'Polo Collar Sweater' },
          { name: 'Shawl Collar Sweater' },
          { name: 'Boat Neck Sweater' },
          { name: 'Cowl Neck Sweater' },
          { name: 'Halter Neck Sweater' },
          { name: 'Henley Neck Sweater' },
          { name: 'High Neck Sweater' },
          { name: 'Mock Neck Sweater' },
          { name: 'Round Neck Sweater' },
          { name: 'Scoop Neck Sweater' },
          { name: 'Square Neck Sweater' },
          { name: 'Surplice Neck Sweater' },
          { name: 'Sweetheart Neck Sweater' },
          { name: 'Turtle Neck Sweater' },
          { name: 'V-Neck Sweater' },
          { name: 'Off-Shoulder Sweater' },
          { name: 'One-Shoulder Sweater' },
          { name: 'Y-Neck Sweater' },
          { name: 'Keyhole Neck Sweater' },
          { name: 'Slit Neck Sweater' },
          { name: 'Sailor Collar Sweater' },
        ],
      },
      {
        name: 'Top',
        thirdCategories: [
          { name: 'Top' },
          { name: 'Bra Top' },
          { name: 'Bustier' },
          { name: 'Camisole' },
          { name: 'Tank Top' },
          { name: 'Tube Top' },
        ],
      },
    ],
  },
  {
    name: 'Bottom',
    subcategories: [
      {
        name: 'Skirt',
        thirdCategories: [
          { name: 'Skirt' },
          { name: 'Cargo Skirt' },
          { name: 'Draped Skirt' },
          { name: 'Five-Pocket Skirt' },
          { name: 'Fringe Skirt' },
          { name: 'Gather Skirt' },
          { name: 'Peasant Skirt' },
          { name: 'Peplum Skirt' },
          { name: 'Pleated Skirt' },
          { name: 'Sarong Skirt' },
          { name: 'Tiered Skirt' },
          { name: 'Wrap Skirt' },
          { name: 'A-Line Skirt' },
          { name: 'Balloon Skirt' },
          { name: 'Hi-Low Skirt' },
          { name: 'Pencil Skirt' },
          { name: 'Flared Skirt' },
          { name: 'Full Skirt' },
          { name: 'Mermaid Skirt' },
          { name: 'Tapered Skirt' },
          { name: 'Trumpet Skirt' },
        ],
      },
      {
        name: 'Pants',
        thirdCategories: [
          { name: 'Pants' },
          { name: 'Baggy Pants' },
          { name: 'Bermuda Shorts' },
          { name: 'Capri Pants' },
          { name: 'Cargo Pants' },
          { name: 'Culottes' },
          { name: 'Sailor Pants' },
          { name: 'Leggings' },
          { name: 'Sarong Pants' },
          { name: 'Sarouel Pants' },
          { name: 'Track Pants' },
          { name: 'Skinny Pants' },
          { name: 'Slim Pants' },
          { name: 'Straight Pants' },
          { name: 'Box Pants' },
          { name: 'Semi-Bootcut Pants' },
          { name: 'Bell-Bottom Pants' },
          { name: 'Wide Pants' },
          { name: 'Palazzo Pants' },
          { name: 'Balloon Pants' },
          { name: 'Jodhpurs' },
          { name: 'Jogger Pants' },
          { name: 'Tapered Pants' },
          { name: 'Chino Pants' },
          { name: 'Dress Pants' },
          { name: 'Five-Pocket Pants' },
          { name: 'Pull-On Pants' },
          { name: 'Training Pants' },
          { name: 'Box Pleats Pants' },
          { name: 'Knickbockers' },
          { name: 'Harem Pants' },
          { name: 'Jamaica Shorts' },
        ],
      },
    ],
  },
  {
    name: 'Outer',
    subcategories: [
      {
        name: 'Coat',
        thirdCategories: [
          { name: 'Coat' },
          { name: 'Balmacaan Coat' },
          { name: 'Cape Coat' },
          { name: 'Chesterfield Coat' },
          { name: 'Duffle Coat' },
          { name: 'Inverness Coat' },
          { name: 'Officer Coat' },
          { name: 'Pea Coat' },
          { name: 'Tailored Coat Double' },
          { name: 'Tailored Coat Single' },
          { name: 'Trench Coat Balmacaan' },
          { name: 'Trench Coat Cape' },
          { name: 'Trench Coat Double' },
          { name: 'Trench Coat Inverness' },
          { name: 'Trench Coat Single' },
          { name: 'Poncho' },
          { name: 'Shawl' },
          { name: 'Fur Coat' },
          { name: 'Shearling Coat' },
          { name: 'Robe' },
          { name: 'Wrap Coat' },
          { name: 'Hood Coat' },
          { name: 'Flat Collar Coat' },
          { name: 'Shawl Collar Coat' },
          { name: 'Shirt Collar Coat' },
          { name: 'Stand Collar Coat' },
          { name: 'V-Neck Coat' },
          { name: 'Round Neck Coat' },
          { name: 'Wing Collar Coat' },
          { name: 'Cocoon Coat' },
        ],
      },
      {
        name: 'Jacket',
        thirdCategories: [
          { name: 'Jacket' },
          { name: 'Blazer' },
          { name: 'Bolero Jacket' },
          { name: 'Chanel Jacket' },
          { name: 'Flat Collar Jacket' },
          { name: 'High Neck Jacket' },
          { name: 'Inverness Jacket' },
          { name: 'Kimono Tunic Jacket' },
          { name: 'Lounge Jacket' },
          { name: 'Military Jacket' },
          { name: 'Norfolk Jacket' },
          { name: 'Peplum Jacket' },
          { name: 'Round Neck Jacket' },
          { name: 'Safari Jacket' },
          { name: 'Shawl Collar Jacket' },
          { name: 'Shirt Collar Jacket' },
          { name: 'Shooting Jacket' },
          { name: 'Tailored Jacket Double' },
          { name: 'Tailored Jacket Single' },
          { name: 'Tuxedo Jacket' },
          { name: 'V-Neck Jacket' },
          { name: 'Wing Collar Jacket' },
          { name: 'Rib Collar Jacket' },
          { name: 'Hood Jacket' },
          { name: 'Square Neck Jacket' },
        ],
      },
      {
        name: 'Casual Jacket',
        thirdCategories: [
          { name: 'Casual Jacket' },
          { name: 'Aviator Jacket' },
          { name: 'Barbour Jacket' },
          { name: 'Biker Jacket' },
          { name: 'Bomber Jacket' },
          { name: 'Field Jacket' },
          { name: 'Harrington Jacket' },
          { name: 'Hunting Jacket' },
          { name: 'Lumber Jacket' },
          { name: 'Souvenir Jacket' },
          { name: 'Stadium Jacket' },
          { name: 'Track Jacket' },
          { name: 'Trucker Jacket' },
          { name: 'Western Jacket' },
          { name: 'Worker Jacket' },
          { name: 'Windbreaker' },
          { name: 'Anorak' },
          { name: 'Poncho' },
          { name: 'Fleece Jacket' },
          { name: 'Quilting Jacket' },
          { name: 'Utility Jacket' },
          { name: 'Shacket' },
          { name: 'Zip Hoodie' },
          { name: 'High Neck Casual Jacket' },
          { name: 'Hooded Casual Jacket' },
          { name: 'Flat Collar Casual Jacket' },
          { name: 'Shirt Collar Casual Jacket' },
          { name: 'Shawl Collar Casual Jacket' },
          { name: 'Round Neck Casual Jacket' },
          { name: 'V-Neck Casual Jacket' },
          { name: 'Rib Collar Casual Jacket' },
          { name: 'Tailored Collar Casual Jacket' },
          { name: 'Wing Collar Casual Jacket' },
        ],
      },
      {
        name: 'Parka',
        thirdCategories: [
          { name: 'Parka' },
          { name: 'Down Parka' },
          { name: 'Quilting Parka' },
          { name: 'Field Parka' },
          { name: 'Flight Parka' },
          { name: 'Mountain Parka' },
          { name: 'Board Parka' },
        ],
      },
      {
        name: 'Cardigan',
        thirdCategories: [
          { name: 'Cardigan' },
          { name: 'Bolero Cardigan' },
          { name: 'Chanel Cardigan' },
          { name: 'Cowichan Cardigan' },
          { name: 'Letter Cardigan' },
          { name: 'Hooded Cardigan' },
          { name: 'Sailor Collar Cardigan' },
          { name: 'Shawl Collar Cardigan' },
          { name: 'Shirt Collar Cardigan' },
          { name: 'High Neck Cardigan' },
          { name: 'Round Neck Cardigan' },
          { name: 'V-Neck Cardigan' },
          { name: 'Twin Set Cardigan' },
          { name: 'Wrap Cardigan' },
        ],
      },
      {
        name: 'Vest',
        thirdCategories: [
          { name: 'Vest' },
          { name: 'Cargo Utility Vest' },
          { name: 'Coat Vest' },
          { name: 'Down Vest' },
          { name: 'Knitted Pullover Vest' },
          { name: 'Knitted Vest Cardigan' },
          { name: 'Quilting Vest' },
          { name: 'Suit Vest' },
          { name: 'Trench Vest' },
          { name: 'Casual Vest' },
        ],
      },
    ],
  },
  {
    name: 'One-Piece',
    subcategories: [
      {
        name: 'Dress',
        thirdCategories: [
          { name: 'Baby-Doll Dress' },
          { name: 'Bustier Dress' },
          { name: 'Chanel Dress' },
          { name: 'Chinese Dress' },
          { name: 'Country Dress' },
          { name: 'Draped Dress' },
          { name: 'Empire Dress' },
          { name: 'Flapper Dress' },
          { name: 'Kaftan Dress' },
          { name: 'Long Torsso Dress' },
          { name: 'Military Dress' },
          { name: 'Peplum Dress' },
          { name: 'Polo Dress' },
          { name: 'Sailor Dress' },
          { name: 'Shirt Dress' },
          { name: 'Slip Dress' },
          { name: 'Smock Dress' },
          { name: 'Tiered Dress' },
          { name: 'Victorian Dress' },
          { name: 'Western Shirt Dress' },
          { name: 'Wrap Dress' },
          { name: 'Off-Shoulder Dress' },
          { name: 'Halter Neck Dress' },
          { name: 'Body-Conscious Dress' },
          { name: 'Slim Dress' },
          { name: 'Box Dress' },
          { name: 'A-Line Dress' },
          { name: 'Fit & Flare Dress' },
          { name: 'Fit & A Dress' },
          { name: 'Trapeze Dress' },
          { name: 'Cocoon Dress' },
          { name: 'Balloon Dress' },
          { name: 'Mermaid Dress' },
          { name: 'Blouson Dress' },
          { name: 'Athletic Dress' },
          { name: 'Utility Dress' },
          { name: 'Twofer Dress' },
          { name: 'Sun Dress' },
          { name: 'T-Shirt Dress' },
          { name: 'Sweater Dress' },
          { name: 'Suit Dress' },
        ],
      },
      { name: 'Jumpsuit', thirdCategories: [{ name: 'Jumpsuit' }] },
      { name: 'Pinafore', thirdCategories: [{ name: 'Pinafore' }] },
      { name: 'Leotard', thirdCategories: [{ name: 'Leotard' }] },
      { name: 'Overall', thirdCategories: [{ name: 'Overall' }] },
    ],
  },
];
